Us7201
edgexfoundry/edgex-global-pipelines pull request #244
Opened 2020-09-11 23:50 UTC by soda480

- Created `edgeXReleaseGitHubAssets` shared library that consumes the `github-release` docker image and embedded tool to create GitHub release with assets.
- Updated `edgeXRelease` shared library to enable support for `gitHubRelease`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:
https://github.com/edgexfoundry/edgex-global-pipelines/issues/242

## Sandbox Testing
Test Links :

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information
```
# gradle clean test
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :test
Results: SUCCESS (194 tests, 192 successes, 0 failures, 2 skipped)

BUILD SUCCESSFUL in 3m 14s
5 actionable tasks: 5 executed
```

2020-09-12 01:35 UTC, bill-mahoney commented on vars/edgeXReleaseGitHubAssets.groovy
> +gitHubRelease: true
should `assets` be a nested object of the `gitHubRelease` somehow?  Just so it gives some context that this applies to the gitHubRelease and not a docker image or something else?  Similar to how `docker` has `image` nested in it.

2020-09-12 01:37 UTC, bill-mahoney submitted a review, later dismissed
Awesome! One less thing to manually release 👍

2020-09-14 17:17 UTC, soda480 commented on vars/edgeXReleaseGitHubAssets.groovy
> +gitHubRelease: true
@bill-mahoney will renaming `assets` to `gitHubReleaseAssets` add the desired clarity?

2020-09-14 17:29 UTC, bill-mahoney commented on vars/edgeXReleaseGitHubAssets.groovy
> +gitHubRelease: true
I think that'll work well, thanks!

2020-09-14 20:44 UTC, soda480 commented on vars/edgeXReleaseGitHubAssets.groovy
> +gitHubRelease: true
done

2020-09-15 15:17 UTC, ernestojeda requested changes
Wow! You got this done already! Just one thing needed. See my comment.

2020-09-15 15:17 UTC, ernestojeda commented on vars/edgeXReleaseGitHubAssets.groovy
> +def createGitHubRelease(releaseInfo, credentials) {
Only thing I see missing here is maybe a DRY_RUN feature.

2020-09-15 18:55 UTC, soda480 commented on vars/edgeXReleaseGitHubAssets.groovy
> +def createGitHubRelease(releaseInfo, credentials) {
added DRY_RUN feature

2020-09-15 22:12 UTC, jamesrgregg approved these changes
👍

2020-09-16 18:17 UTC, bill-mahoney approved these changes
👍

2020-09-17 01:45 UTC, ernestojeda commented on vars/edgeXReleaseGitHubAssets.groovy
> +def call(releaseInfo, credentialsId = 'edgex-jenkins-github-personal-access-token') {
Be careful with this ID. It may no be consistent between the Sandbox and Production servers

2020-09-17 01:45 UTC, ernestojeda reviewed
See comments.

2020-09-17 03:43 UTC, soda480 commented on vars/edgeXReleaseGitHubAssets.groovy
> +def call(releaseInfo, credentialsId = 'edgex-jenkins-github-personal-access-token') {
Updated to have script determine `credentialsId` based on environment.

2020-09-17 16:35 UTC, ernestojeda approved these changes
LGTM

2020-09-17 17:11 UTC, merged