fix(idea): Remove .idea files & update gitignore
edgexfoundry/edgex-global-pipelines pull request #278
Opened 2020-10-20 22:58 UTC by cjoyv

Signed-off-by: Chinu Joy <chinu.joy@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:

## Sandbox Testing
Test Links :

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-10-20 23:02 UTC, bill-mahoney submitted a review, later dismissed
LGTM

2020-10-21 03:24 UTC, soda480 submitted a review, later dismissed

2020-10-21 15:39 UTC, ernestojeda commented
I am pulling this PR locally and verifying it does not cause problems

2020-10-21 15:50 UTC, ernestojeda requested changes
Need to figure out another way to do this. Removing these XML files does not allow easily testing and debugging unit tests

2020-10-21 16:50 UTC, closed without merging