feat(jenkins): Shared library for github-pages publish
edgexfoundry/edgex-global-pipelines pull request #283
Opened 2020-10-22 21:25 UTC by cjoyv

Signed-off-by: Chinu Joy <chinu.joy@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:

## Sandbox Testing
Test Links :

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-10-29 02:12 UTC, soda480 requested changes
just a few cosmetic changes, and one question regarding unnecessary mocks

2020-10-29 02:12 UTC, soda480 commented on src/test/groovy/edgeXGHPagesPublishSpec.groovy
> +            edgeXGHPagesPublish.getBinding().setVariable('env', environmentVariables)
not necessary to set DRY_RUN environment variable when testing this condition, I now it doesn't hurt anything, but it adds unnecessary lines of code to your unit test.

2020-10-29 02:12 UTC, soda480 commented on src/test/groovy/edgeXGHPagesPublishSpec.groovy
> +            getPipelineMock('dir').call(_)
is all this mocking (dir, withEnv, sh, unstash) necessary?  i don't think it is, if not could eliminate unnecessary lines of code in your unit test.

2020-10-29 19:05 UTC, ernestojeda requested changes
See comments

2020-10-29 19:05 UTC, ernestojeda commented on Jenkinsfile
> +                    edgeXGHPagesPublish(repoUrl: "git@github.com:edgexfoundry/edgex-global-pipelines.git")
One thing I think would make this more complete is if we allowed the GitHub pages branch to be configureable. Something like branch: ‘gh-pages’

2020-10-29 19:05 UTC, ernestojeda commented on resources/github-pages-publish.sh
> +    git push origin gh-pages
Configureable branch name

2020-10-29 19:05 UTC, ernestojeda commented on vars/edgeXGHPagesPublish.groovy
> +        dir('edgex-docs-clean') {
This directory should not be named edgex-docs-clean. Maybe something more generic

2020-10-29 19:05 UTC, ernestojeda commented on vars/edgeXGHPagesPublish.groovy
> +            git url: "${repoUrl}", branch: 'gh-pages', credentialsId: "${credentialId}", changelog: false, poll: false
Configureable branch name

2020-10-29 19:05 UTC, ernestojeda commented on vars/edgeXGHPagesPublish.groovy
> +            unstash 'site-contents'
Configureable stash name maybe ??

2020-10-30 00:19 UTC, cjoyv commented on Jenkinsfile
> +                    edgeXGHPagesPublish(repoUrl: "git@github.com:edgexfoundry/edgex-global-pipelines.git")
yes, we can keep it default to `gh-pages` if not provided

2020-10-30 00:20 UTC, cjoyv commented on src/test/groovy/edgeXGHPagesPublishSpec.groovy
> +            getPipelineMock('dir').call(_)
Done

2020-10-30 00:20 UTC, cjoyv commented on src/test/groovy/edgeXGHPagesPublishSpec.groovy
> +            edgeXGHPagesPublish.getBinding().setVariable('env', environmentVariables)
Done

2020-10-30 02:50 UTC, soda480 approved these changes

2020-10-30 15:01 UTC, ernestojeda commented on vars/edgeXGHPagesPublish.groovy
> +            unstash "${stashName}"
this can just be:

```Groovy
unstash stashName
```

2020-10-30 15:02 UTC, ernestojeda commented on vars/edgeXGHPagesPublish.groovy
> +            git url: "${repoUrl}", branch: "${ghPagesBranch}", credentialsId: "${credentialId}", changelog: false,
This can just be:

```Groovy
git url: repoUrl, branch: ghPagesBranch, credentialsId: credentialId, changelog: false, poll: false
```

2020-10-30 15:05 UTC, ernestojeda approved these changes
Looks good. There is some unnecessary string interpolation used in `vars/edgeXGHPagesPublish.groovy` but we can fix that later.

2020-10-30 15:05 UTC, ernestojeda commented on vars/edgeXGHPagesPublish.groovy
> +                sshagent(credentials: ["${credentialId}"]) {
```Groovy
sshagent(credentials: [credentialId]) {
````

2020-10-30 18:45 UTC, merged