docs(jenkins): Add documentation for unit testing prescriptive guidance
edgexfoundry/edgex-global-pipelines pull request #290
Opened 2020-11-02 16:18 UTC by soda480

Add documentation describing prescriptive guidance for facilitating unit testing of Jenkins declarative pipeline logic.

Signed-off-by: Emilio Reyes <emilio.reyes@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:
Fixes https://github.com/edgexfoundry/edgex-global-pipelines/issues/194

## Sandbox Testing
NA

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-11-02 16:21 UTC, cjoyv submitted a review, later dismissed
LGTM

2020-11-02 16:23 UTC, bill-mahoney approved these changes
LGTM

2020-11-02 16:33 UTC, ernestojeda requested changes
An example would be nice here

2020-11-02 16:33 UTC, ernestojeda commented on docs_src/tutorials/unit-testing-guidance.md
> +The edgex-global-pipelines shared library leverages the [Jenkins Spock framework](https://github.com/ExpediaGroup/jenkins-spock) for unit testing Jenkins pipeline scripts and functions. The Jenkins S
Can you add a link to declarative pipeline when you mention "[Jenkins declarative pipeline](https://www.jenkins.io/doc/book/pipeline/syntax/#declarative-pipeline)"

2020-11-02 16:33 UTC, ernestojeda commented on docs_src/tutorials/unit-testing-guidance.md
> +In order to facilitate unit testing of the edgex-global-pipelines shared library, the DevOps team has made a deliberate effort to to minimize the amount of scripting logic contained within Jenkins de
Can we get an example of this?

2020-11-02 17:03 UTC, soda480 commented on docs_src/tutorials/unit-testing-guidance.md
> +In order to facilitate unit testing of the edgex-global-pipelines shared library, the DevOps team has made a deliberate effort to to minimize the amount of scripting logic contained within Jenkins de
done

2020-11-02 20:32 UTC, bill-mahoney submitted a review, later dismissed
LGTM, I like the example too

2020-11-03 15:30 UTC, ernestojeda approved these changes
Looks great. Thanks for the example.

2020-11-03 15:36 UTC, merged