Add ability to release at commit SHA - DO NOT REMOVE - DO NOT MERGE
edgexfoundry/edgex-global-pipelines pull request #308
Opened 2021-01-11 16:14 UTC by soda480

Signed-off-by: Emilio Reyes <emilio.reyes@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:

## Sandbox Testing
Test Links :

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-01-12 00:19 UTC, cjoyv commented on src/test/groovy/edgeXReleaseGitTagSpec.groovy
> +    def "Test bumpAndPushGitTag [Should] call edgeXSemver bump and push [When] DRY_RUN is false and bump is false" () {
@soda480 I think there is a typo here, bump is `pre ` instead of `false`

2021-01-12 00:26 UTC, cjoyv approved these changes
LGTM

2021-01-12 00:26 UTC, cjoyv commented on src/test/groovy/edgeXReleaseGitTagSpec.groovy
> +    def "Test bumpAndPushGitTag [Should] call edgeXSemver bump and push [When] DRY_RUN is false and bump is false" () {
I think my bad, I confused it with bumpLevel. you are good 👍

2021-01-12 19:19 UTC, bill-mahoney submitted a review, later dismissed
LGTM, nice 👍

2021-01-13 17:45 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
> +                                        if(${params.CommitId}) {
this can just be `if(params.CommitId) {`

2021-01-13 17:46 UTC, ernestojeda requested changes
See comments about `params.CommitId`

2021-01-13 17:46 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
> +                                        if(${params.CommitId}) {
this can just be `if(params.CommitId) {`

2021-01-13 18:04 UTC, soda480 commented on vars/edgeXBuildCApp.groovy
> +                                        if(${params.CommitId}) {
ok

2021-01-13 18:04 UTC, soda480 commented on vars/edgeXBuildCApp.groovy
> +                                        if(${params.CommitId}) {
ok

2021-01-15 16:33 UTC, ernestojeda approved these changes
Nice job 👍🏽

2021-01-15 16:35 UTC, merged