doc: Update the documentation for the following pre-built pipelines
edgexfoundry/edgex-global-pipelines pull request #325
Opened 2021-03-18 18:58 UTC by cjoyv

doc: Update the documentation for the following pre-built pipelines: edgeXBuildGoMod,edgeXBuildDocker,edgeXBuildCApp

Signed-off-by: Chinu Joy <chinu.joy@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:

## Sandbox Testing
Test Links :

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-03-19 23:51 UTC, bill-mahoney submitted a review, later dismissed
LGTM

2021-03-23 18:08 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
> + ![edgeXBuildCApp](images/edgeXBuildCApp.png)
The text in this image is harder to read than `edgeXBuildGoApp` for instance. Can you somehow make it bigger?

2021-03-23 18:29 UTC, ernestojeda requested changes
Mostly minor changes

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
> + project: 'device-sdk-c',
Lets make this a bit more complex.

```Groovy
edgeXBuildCApp (
    project: 'device-sdk-c',
    dockerBuildFilePath: 'scripts/Dockerfile.alpine-3.11-base',
    dockerFilePath: 'scripts/Dockerfile.alpine-3.11',
    testScript: 'apk add --update --no-cache openssl ca-certificates && make test',
    pushImage: false
)
```

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
> + project: 'device-bacnet-c',
I think the basic example should look like this:

```Groovy
edgeXBuildCApp (
    project: 'device-bacnet-c'
)
```

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
>   ## Usage
Can you fix the indentation in all the examples below?

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildCApp.groovy
> + failureNotify | optional | str | The group emails (comma-delimited) to email when the Jenkins job fails.<br /><br />**Default**: `edgex-tsc-core@lists.edgexfoundry.org,edgex-tsc-devops@lists.edgexfo
There is a missing parameter we need to add to all of these pipelines...

```
arch | optional | array | A list of system architectures to target for the build. Possible values are `amd64` or `arm64`.<br /><br />**Default**: ['amd64', 'arm64']
```

We you will also need to add this to the final example with all the parameters.

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildDocker.groovy
> + ![edgeXBuildDocker](images/edgeXBuildDocker.png)
Same comment about the font size...pretty hard to read in this image.

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildDocker.groovy
>   ## Usage
Same comment about the indentation in the examples below.

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildDocker.groovy
>   ### Complex example
Lets use this for the complex example:

```Groovy
edgeXBuildDocker ([
    project: 'edgex-compose',
    mavenSettings: 'ci-build-images-settings',
    dockerImageName: 'custom-edgex-compose',
    dockerNamespace: 'edgex-devops',
    dockerNexusRepo: 'snapshots',
    dockerTags: ["1.24.1"],
    releaseBranchOverride: 'edgex-compose'
])
```

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildDocker.groovy
> + failureNotify | optional | str | The group emails (comma-delimited) to email when the Jenkins job fails.<br /><br />**Default**: `edgex-tsc-core@lists.edgexfoundry.org,edgex-tsc-devops@lists.edgexfo
Same comment about the missing hidden setting:

```
arch | optional | array | A list of system architectures to target for the build. Possible values are `amd64` or `arm64`.<br /><br />**Default**: ['amd64', 'arm64']
```
We you will also need to add this to the final example with all the parameters.

2021-03-23 18:29 UTC, ernestojeda commented on vars/edgeXBuildGoMod.groovy
> + ## Usage
Looks good, just need to updated all the indentation.

2021-03-23 21:58 UTC, soda480 commented on vars/edgeXBuildCApp.groovy
> + ![edgeXBuildCApp](images/edgeXBuildCApp.png)
I noticed that as well, seems like your images don't have the same shadow effect that `edgeXBuildGoApp` has. It would be nice if all the images (used through out the documentation) have the same look and feel.

2021-03-24 21:12 UTC, soda480 approved these changes
Looks great.

2021-03-24 21:18 UTC, ernestojeda approved these changes
LGTM

2021-03-25 17:20 UTC, merged